# Generated by Django 3.0.6 on 2020-07-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200712_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='child_nodes',
            field=models.ManyToManyField(related_name='_node_child_nodes_+', to='stories.Node'),
        ),
        migrations.AddField(
            model_name='post',
            name='first_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.Node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='action',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
