# Generated by Django 3.0.6 on 2020-07-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200712_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='child_nodes',
            field=models.ManyToManyField(to='stories.Node'),
        ),
    ]
