# Generated by Django 3.0.6 on 2020-07-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20200712_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Post'),
        ),
    ]
