# Generated by Django 3.0.6 on 2020-07-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20200715_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='parent_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='stories.Node'),
        ),
    ]
