# Generated by Django 3.0.8 on 2020-07-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genres',
            field=models.ManyToManyField(to='stories.Genre'),
        ),
    ]
