# Generated by Django 3.0.8 on 2020-07-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20200721_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genres',
            field=models.ManyToManyField(blank=True, to='stories.Genre'),
        ),
    ]
